package firehose

import (
	"fmt"
	"time"
)

// DefaultFetchConfig returns the built-in fetch settings, used also for tools
// that do not depend on a live config file, such as `firehose test...`
func DefaultConfig() *Config {
	return &Config{
		Settings: Settings{
			DisplayWindow:      Duration(14 * 24 * time.Hour),
			CacheRetention:     Duration(30 * 24 * time.Hour),
			Body:               BodyFull,
			ExcerptWords:       60,
			ExcerptImage:       ExcerptImageNone,
			Theme:              "auto",
			Typography:         true,
			ReadingTime:        true,
			Highlight:          true,
			Dedupe:             true,
			HighlightTheme:     "github",
			HighlightThemeDark: "github-dark",
		},
		Fonts: FontConfig{
			ContentFamily: defaultContentFamily,
			ChromeFamily:  defaultChromeFamily,
			// CSSURL deliberately unset: whether the remote default applies
			// depends on whether self-hosted sources are configured. See
			// Config.FontsCSSURL.
		},
		Fetch: DefaultFetchConfig(),
	}
}

func DefaultFetchConfig() FetchConfig {
	return FetchConfig{
		Concurrency:    defaultConcurrency,
		PerHostSerial:  true,
		Timeout:        Duration(defaultTimeout),
		UserAgent:      defaultUserAgent,
		AcceptLanguage: defaultAcceptLanguage,
	}
}

// compactDuration renders a duration in the terse form the config uses
// ("336h", "20s") rather than time.Duration's "336h0m0s".
func compactDuration(d time.Duration) string {
	switch {
	case d%time.Hour == 0:
		return fmt.Sprintf("%dh", d/time.Hour)
	case d%time.Minute == 0:
		return fmt.Sprintf("%dm", d/time.Minute)
	default:
		return fmt.Sprintf("%ds", d/time.Second)
	}
}

// DefaultConfigTOML returns a complete, annotated configuration with every
// option shown at its default value, Options with no default are shown
// commented.
func DefaultConfigTOML() string {
	d := DefaultConfig()
	return fmt.Sprintf(`# firehose configuration
# Generated by "firehose init". Every option is shown with its default value;
# commented options have no default and are optional. Resolution for body,
# excerpt_image, and reading_time is three-tier: settings -> output -> feed.

[settings]
output_dir      = "/var/www/firehose"          # generated HTML written here (required)
cache_db        = "/var/lib/firehose/cache.db" # fetch cache; disposable by design (required)
display_window  = %q     # how much river renders (14 days)
cache_retention = %q     # GUID/dedupe history; must be >= display_window (30 days)
# timezone      = "America/Vancouver"  # IANA name; default: system local time
body            = %q     # title | excerpt | full | excerpt+expand
excerpt_words   = %d     # word budget for excerpt scopes
excerpt_image   = %q     # lead | none: first image in excerpts
theme           = "auto" # auto | light | dark; the in-page toggle overrides per browser
typography      = true   # normalize quotes/dashes/ellipses (never inside code)
reading_time    = true   # show "~N min" in the item meta line
highlight       = true   # highlight ONLY declared languages; never guess
dedupe          = true   # collapse the same story arriving via multiple feeds (canonical-URL identity)
highlight_theme = %q     # chroma style names (light / dark mode)
highlight_theme_dark = %q
links_new_tab   = false  # open story links in a new tab/window (site nav stays in-tab)
# note_template = "https://example.org/notes/new?title={title}&url={url}"  # per-item "note" link

[fetch]
concurrency     = %d     # bounded fetch worker pool
per_host_serial = true   # never fetch two feeds from one host concurrently
timeout         = %q
user_agent      = %q
accept_language = %q     # browsers always send it; absence is a bot tell

[fonts]
# Webfonts load from a remote stylesheet by default (Google Fonts, covering
# the default families below). To self-host instead, set the src lines — a
# remote stylesheet is then no longer defaulted. If you change the families,
# change css_url to match (or self-host).
content_family  = %q
chrome_family   = %q
css_url         = %q
# content_src   = "/fonts/CrimsonPro.woff2"
# chrome_src    = "/fonts/IBMPlexSans.woff2"

# Outputs: each [[output]] is a rendered river page; a section is a filter.
# The unlinked firehose.html health page is always generated in addition.
[[output]]
name       = "all"
file       = "index.html"
title      = "Everything"
categories = ["*"]       # the ALL river
body       = "excerpt"   # keep the firehose page scannable

[[output]]
name       = "example"
file       = "example.html"
title      = "Example Section"
categories = ["example"]

# Feeds: categories place a feed into sections; a feed may have several.
[[feed]]
url        = "https://example.org/feed.xml"
categories = ["example"]
# title           = "Override Title"    # wins over the feed's self-reported title
# body            = "excerpt+expand"    # per-feed override
# excerpt_image   = "lead"
# Per-feed UA override. Probe with and without when adding a new feed as some CDNs
# block our honest robot UA, while others welcome it. firehose test | firehose test -ua "Mozilla..."
# user_agent      = "Mozilla/5.0 ..."
# headers         = { "Accept-Language" = "en-CA" }  # extra request headers
# exclude         = ["sponsored"]       # drop items matching these keywords
#                     # (include/exclude match title, body, and description)
# include         = []                  # keep only matching items
# strip_selectors = ["div.sharedaddy"]  # remove cruft nodes post-parse
# A local feed document (e.g. from a scraper). Can be a bare absolute path.
# [[feed]]
# url        = "file:///var/lib/hydrant/feeds/site.xml"
# categories = ["scraped"]
# display_window  = "1440h"             # per-feed window (slow civic feeds); must fit cache_retention
# Fix feeds that emit another site's hostname in item links and GUIDs.
# A key matches itself and its subdomains ("wrong.example" covers www).
# rewrite_host    = { "wrong.example" = "right.example" }
`,
		compactDuration(d.Settings.DisplayWindow.D()),
		compactDuration(d.Settings.CacheRetention.D()),
		string(d.Settings.Body),
		d.Settings.ExcerptWords,
		string(d.Settings.ExcerptImage),
		d.Settings.HighlightTheme,
		d.Settings.HighlightThemeDark,
		defaultConcurrency,
		compactDuration(defaultTimeout),
		defaultUserAgent,
		defaultAcceptLanguage,
		defaultContentFamily,
		defaultChromeFamily,
		defaultFontsCSSURL,
	)
}
